### PR TITLE
Implement read-only mounts

### PR DESCRIPTION
**Pull request by kolyshkin**
This changes the syntax of moctl mount to be closer to one of mount, adds -r option, and fixes ploop cloning vs read-write mounts case. Depends on previous two pull requests I guess.

### CODE REVIEW

**Comment by xemul** [comment]
Kir, GitHub obviously doesn't work well with several pull requests from a single branch. In particular I've merges the attach/detach one, but these commits are still here.

**Comment by kolyshkin** [comment]
> I don't like this usage. Let's get back to the on we had:
> 
> moctl NAME mount {VOLUME|-} MOUNTPOINT FLAGS
> 
> FLAGS are comma-separated values, can be - for none. ro means read-only.

I don't like this syntax if yours on so many levels. In particular:
1. In most cases we don't need to specify any mount flags. Asking users to put - in there is just wrong.
2. All the tools I see that does some kind of mounting (including mount, ploop, fuse modules) allow to use `-r` or `-o ro` for read-only mounts. I vote to not be different and confuse users unless we gain something from it.
3. I dislike positional arguments in general. Some limited use is OK, like `NAME COMMAND` in `moctl`, or as in vzctl (`vzctl COMMAND VEID`). Having said that, even in vzctl it's proven to be problematic (`vzctl snapshot-list --list-fields` has to become `vzctl snapshot-list VEID --list-fields` although `VEID` is not required in there). Utility `ip` is an exception because it is nicely structured and in fact is modelled after Cisco IOS command line (too long to explain).

Please explain why you feel that having positional flags argument is better than traditional "flags/options" notation.

**Comment by kolyshkin** [comment]
> Why unset_var? It unlinks a file...
> These three functions (read/write/unset var) serve a purpose of having a very simple key-value storage local to a ploop volume.

Think of say shell variables -- a variable can be assigned a value (write), you can use this value (read), or a variable can be non-existent (not set). There is a distinction between variable with empty value and an unset variable.

For the puprose I am using these *_var() functions here, I can live with just writing a single value to a file -- let me know if you prefer it this way.

**Comment by kolyshkin** [comment]
> Kir, GitHub obviously doesn't work well with several pull requests from a single branch.
> In particular I've merges the attach/detach one, but these commits are still here.

I see this, too, and have to rebase and push once you merge dependent pull requests.
I will try to not do pull reqs depending on each other, but the current ones are all dependent as we are still building the frame.

**Comment by kolyshkin** [comment]
If you are trying to model the synopsis after `ip`, it would be something like:

`moctl NAME mount MOUNTPOINT [volume VOLUME] [flags FLAGS]`

In other words, in `ip` not all arguments are positional, it's just instead of `--option ARG` they use `option ARG`. You, on the other hand, insist on just `ARG` which doesn't look good to me.

**Comment by xemul** [comment]
I guess this will be heavily reworked, right?

**Comment by xemul** [comment]
On 09/30/2015 10:40 AM, Kirill Kolyshkin wrote:

> ```
> I don't like this usage. Let's get back to the on we had:
> 
> moctl NAME mount {VOLUME|-} MOUNTPOINT FLAGS
> 
> FLAGS are comma-separated values, can be - for none. ro means read-only.
> ```
> 
> I don't like this syntax if yours on so many levels. In particular:
> 1. In most cases we don't need to specify any mount flags. Asking users to put - in there is just wrong.

Fine, let's support empty flags.

> 1. All the tools I see that does some kind of mounting (including mount, ploop, fuse modules) allow to
>    use |-r| or |-o ro| for read-only mounts. I vote to not be different and confuse users unless we gain 
>    something from it.

No problem, let's add -o ro, but not separate -r one.

> 1. I dislike positional arguments in general. Some limited use is OK, like |NAME COMMAND| in |moctl|,
>    or as in vzctl (|vzctl COMMAND VEID|). Having said that, even in vzctl it's proven to be problematic
>    (|vzctl snapshot-list --list-fields| has to become |vzctl snapshot-list VEID --list-fields| although
>    |VEID| is not required in there). Utility |ip| is an exception because it is nicely structured and in fact is modelled after Cisco IOS command line (too long to explain).
> 
> Please explain why you feel that having positional flags argument is better than traditional "flags/options" notation.

I don't like when mandatory arguments have to be preceded with some keyword. IOW

  moctl mount - /foo

is much much better than

  moctl mount --what mosaic --where-to /foo

I'm OK with optional options though, like -o one.

**Comment by kolyshkin** [comment]
Yes, I was working on all three in parallel, will rework.

**Comment by kolyshkin** [comment]
> I don't like when mandatory arguments have to be preceded with some keyword.

It depends. If there are many arguments (say more than 2 or 3) I'd rather not rely on user putting all them in the correct order. If some are optional, they'd rather not be positional (adding `-` looks silly). Otherwise I'm fine with it.

**Pull request closed without merging**
