### PR TITLE
Implement "is volume exists" functionality

### PR DESCRIPTION
**Pull request by kolyshkin**
It's only the last patch that does it, all the others are some random fixes for bugs I found while working on it.

Please review carefully.

### CODE REVIEW

**Comment by kolyshkin** [comment]
I also think, maybe we can nuke `mosaic_open_volume`, it's kinda useless the way it is now.

**Comment by xemul** [comment]
The idea of removing ->open callback is not nice. We can make it optional and force generic level mosaic_open_volume() call ->exists_vol() instead if absent.

**Comment by kolyshkin** [comment]
> The idea of removing ->open callback is not nice.

I have two reasons to not like `open_volume` the way it is now:
1 it doesn't really open\* anything, it's more like a constructor (so `init` or `get` (and `put` instead of `close`) are way more appropriate than `open`), and it terms of driver, it's not even a constructor, but an `exists` call.
2 it doesn't have a matching `close_volume` callback in the driver (that reinforces my understanding that nothing is really opened)
- in my understanding to open something means to change its state

> We can make it optional and force generic level mosaic_open_volume()
> call ->exists_vol() instead if absent.

OK, I'll rework the patchset.

**Comment by kolyshkin** [comment]
OK here's v2, The major changes are:
1. rename `exists_volume` to `have_volume`, same for other function names and moctl command
2. make the exists_volume() callback required
3. add a patch to drop open_volume driver callback (see details in the last patch)

Note that with this in place, we can easily re-add optional per-driver `open_volume` (and `close_volume` which is absent now!) callbacks whenever a need from a particular driver arises, and call them from `get_volume` and `put_volume`, respectively.

**Comment by kolyshkin** [comment]
Just in case you don't like `get_volume()` and `put_volume()` names, let me know how do you want me to rename these.

I was thinking about `init`/`fini`, `alloc_vol_handle`/`free_vol_handle` etc., chose `get`/`put` as a simplest version

**Comment by xemul** [comment]
->open_volume ->close_volume is OK

**Comment by kolyshkin** [comment]
OK here's v3, `mosaic_open_vol` is coming back, but all the goodies from the previous version are still here. In particular, open_volume callback is optional, and open/close is now balanced, meaning:
1. In mosaic API, If you call `mosaic_open_vol` and it succeeded, you must call `mosaic_close_vol` later.
2. A backend can choose to implement `open_volume` and `close_volume` callbacks.

**Comment by xemul** [comment]
Thanks. One more comment from previous attempt went unnoticed -- plz, add flags argument to mosaic_have_vol() API call

**Comment by kolyshkin** [comment]
> plz, add flags argument to mosaic_have_vol() API call

Yep, I overlooked it, thought you were talking about open().

Added.

**Pull request merged**
